---
- name: Install PHP
  apt: name={{ item }} state=latest
  sudo: True
  with_items:
    - php5
    - php5-mysql
    - php5-curl
    - php5-fpm
    - php5-cli
    - php5-cgi
    - php5-dev
    - php-pear
    - php5-gd
    - php-apc
    - php5-gd
    - php-soap
    - php5-xmlrpc
    - php5-mcrypt

